Caio subs controller
OpenDevUFCG/Margaret pull request #12
Opened 2020-10-14 09:19 UTC by caiodavic

base implementation SubscribedsController and MentorController. Add state in mentor.py

2020-10-14 11:44 UTC, JuanBarros2 requested changes

2020-10-14 11:44 UTC, JuanBarros2 commented on python/mentor.py
> +    def organization(self,value):
Como não tem nenhuma lógica de negócio nesse setter, não é preciso cria-lo

2020-10-14 11:44 UTC, JuanBarros2 commented on python/MentorController.py
> +            print(error)
Como combinamos, o ideal agora é abandonar os prints e tentar só gerar a Exception mesmo

2020-10-14 11:44 UTC, JuanBarros2 commented on python/SubscribedsController.py
> +           if value_attribute.lower() in getattr(sub,attribute):
Nice!

2020-10-14 11:44 UTC, JuanBarros2 commented on python/SubscribedsController.py
> +            self.email_validacion(new_attribute)
email_ _validation_

2020-10-14 14:22 UTC, gabriellytrajano commented on python/SubscribedsController.py
> +        subscribed = Subscribed(name,email,discord,period,minoritary_group)
acho que o nome deveria ser subscriber, e a lista subscribers

2020-10-15 13:31 UTC, huandrey approved these changes

2020-10-15 23:38 UTC, ummatias approved these changes

2020-10-17 18:59 UTC, caiodavic commented on python/SubscribedsController.py
> +                return email
A mudança do print aq

2020-10-18 20:36 UTC, JuanBarros2 commented on python/user.py
>  import re
Não precisa mais desse import

2020-10-18 20:36 UTC, JuanBarros2 commented on python/subscribeds_controller.py
> +        if attribute == 'email':
Não precisa verificar. Quando usamos o setattr ele vai validar lá no objeto

2020-10-18 20:36 UTC, JuanBarros2 commented on python/mentor_controller.py
> +        if attribute == 'email':
Pode remover também

2020-10-19 14:40 UTC, JuanBarros2 approved these changes

2020-10-19 14:50 UTC, merged