refactoring class project
OpenDevUFCG/Margaret pull request #13
Opened 2020-10-14 14:22 UTC by gabriellytrajano

* falta um método *

2020-10-15 13:20 UTC, huandrey requested changes

2020-10-15 15:48 UTC, caiodavic approved these changes

2020-10-15 15:48 UTC, caiodavic approved these changes

2020-10-16 13:59 UTC, JuanBarros2 commented on python/project.py
>  		return self.areas
Acho que isso acontece pq ele fica em dúvida se a pessoa ta chamando o atributo ou a funcao em si (Python é uma linguagem funcional, isso quer dizer que ela tem algumas características diferentes que vocês podem estranhar, exemplo: Uma função pode ser guardada em uma variável) e aí acaba chamando sempre a função na hora de atribuir, gerando uma recursão (Não tenho certeza)

2020-10-17 18:05 UTC, ummatias approved these changes

2020-10-17 22:52 UTC, huandrey commented on python/project.py
>  		return self.areas
Faz muito sentindo ser isso mesmo!! 🚀

2020-10-20 20:22 UTC, huandrey approved these changes

2020-10-21 22:31 UTC, merged