Resolvendo conflitos pendentes pós pair programming
OpenDevUFCG/Margaret pull request #22
Opened 2020-10-22 00:27 UTC by huandrey

2020-10-26 22:43 UTC, JuanBarros2 commented on python/app.py
> +    return jsonify(project)
Isso funcionou? :thinking: Acho que ele só aceita se for dicionário

2020-10-26 22:43 UTC, JuanBarros2 commented on python/__tests__/test_project_controller.py
> +    assert project.get('state') == 'Em análise'
Tu tentou usar direto o 'project.state' ? Acho que funciona

2020-10-26 22:43 UTC, JuanBarros2 commented on python/__tests__/test_project_controller.py
> +    assert project.get('areas') == 'Web'
Mesma coisa aqui

2020-10-26 22:43 UTC, JuanBarros2 commented on python/__tests__/test_project_controller.py
> +    assert project.get('name') == 'IssueAi'
Mesma coisa aqui

2020-10-27 00:42 UTC, huandrey commented on python/app.py
> +    return jsonify(project)
É que eu já converto ele pra dicionário na própria função
[Trecho do Código](https://drive.google.com/file/d/1VCRmadIgqLxJGSUQWrLmp5Ym5FJWpQ3Q/view?usp=sharing)

2020-10-27 00:42 UTC, huandrey commented on python/__tests__/test_project_controller.py
> +    assert project.get('state') == 'Em análise'
hmmm, deve funcionar!!

2020-10-27 00:43 UTC, huandrey commented on python/__tests__/test_project_controller.py
> +    assert project.get('name') == 'IssueAi'
okss!!

2020-10-27 12:25 UTC, JuanBarros2 commented on python/app.py
> +    return jsonify(project)
Minha intuição diz que não é uma coisa boa de se fazer porque ele pode perder as funcionalidades dos sets e gets quando se tentar acessar essa variável, já que ela não é mais um objeto e sim um dicionário. Acho melhor só converter na hora de retornar mesmo

2020-10-28 19:21 UTC, caiodavic approved these changes

2020-11-02 22:41 UTC, huandrey commented on python/app.py
> +    return jsonify(project)
Uhum, fiz isso por causa dos métodos, muitos deles é de "find alguma coisa". 
Pq assim, como eu buscaria os valores do projeto ele tando em formato de objeto do tipo Project? 
Eu teria isso dentro do self.projects por ex:
`1: <__main__.Project object at 0x7f2ad0b5ac10>`
Dai no caso, daria certo eu transformar esses projetos para dicionários apenas nos outros métodos quando eu precisar?

2020-11-02 22:55 UTC, huandrey commented on python/app.py
> +    return jsonify(project)
Ah nãooo, ignora!! kkkkk 
Eu que compliquei o trem, dá pra fazer as coisas bem mais simples

2020-11-04 20:37 UTC, huandrey commented on python/app.py
> +    return jsonify(project)
**Refatoração feita!!**

2020-11-04 20:39 UTC, huandrey commented on python/__tests__/test_project_controller.py
> +    assert project.get('state') == 'Em análise'
Modifiquei aqui!

2020-11-05 18:41 UTC, JuanBarros2 requested changes

2020-11-05 18:41 UTC, JuanBarros2 commented on python/__tests__/test_project_controller.py
> +    project = collections.projects[1]
Aqui o ideal é testar se ao executar `find_projects_by_area` ele vai retornar os projetos corretamente

2020-11-05 18:41 UTC, JuanBarros2 commented on python/__tests__/test_project_controller.py
> +    project = collections.projects[1]
Aqui o ideal é testar se ao executar `find_projects_by_state` ele vai retornar os projetos corretamente

2020-11-07 00:34 UTC, huandrey commented on python/__tests__/test_project_controller.py
> +    project = collections.projects[1]
Eu pensei em fazer assim, tu acha uma boa ou tem alguma sugestão?
    
    collections = ProjectController()

    collections.add_project('Margaret', '', '', '', '', '') 
    collections.add_project('Roadmap', '', '', '', '', '') 
    collections.add_project('Laguinho', '', '', '', '', '') 
    collections.update_project_state(1, 'Aprovado')
    projects = collections.find_projects_by_state('Em análise')
    
    assert len(list(projects)) == 2

2020-11-07 13:04 UTC, JuanBarros2 commented on python/controllers/project_controller.py
> +from models.project import Project
isso aqui ta funcionando sem o "python" na frente? 🤔

2020-11-07 13:05 UTC, JuanBarros2 commented on python/controllers/project_controller.py
> +                found_projects.update({key + 1: val})
Não entendi porque ficou key+1

2020-11-07 13:08 UTC, JuanBarros2 commented on python/controllers/project_controller.py
> +    def update_project_description(self, current_id, new_description):
Aqui acho que esses códigos de update estão se repetindo muito. Acho que daria pra receber apenas o campo que você quer modificar e usar o [setattr()](https://www.programiz.com/python-programming/methods/built-in/setattr) para evitar repetir a função 3 vezes

2020-11-07 13:10 UTC, JuanBarros2 commented on python/controllers/project_controller.py
> +            return self.projects
Aqui a ideia é retornar apenas o que foi excluído, não a lista toda

2020-11-07 13:12 UTC, JuanBarros2 commented on python/controllers/project_controller.py
> +            if project.mentor.email == email_mentor or project.mentor_aux.email == email_mentor:
Acho que em vez de fazer essa verificação no controller, tu pode colocar dentro de Project uma função que recebe o email e faz isso pra tu. Fica mais coeso o código uma vez que é o Project que tem os campos de mentor e mentor_aux

2020-11-10 14:24 UTC, JuanBarros2 commented on python/models/project.py
> +        if email == mentor["email"]:
```suggestion
        return email == mentor["email"]
```

2020-11-10 14:24 UTC, JuanBarros2 commented on python/models/project.py
> +        if self.mentor.email == email or self.aux_mentor.email == email:
```suggestion
        return self.mentor.email == email or self.aux_mentor.email == email
```

2020-11-10 14:24 UTC, JuanBarros2 commented on python/models/project.py
> +    @ property
```suggestion
    @property
```

2020-11-10 14:24 UTC, JuanBarros2 commented on python/models/project.py
> +    @ state.setter
```suggestion
    @state.setter
```

2020-11-10 14:24 UTC, JuanBarros2 commented on python/__tests__/test_project_controller.py
> +        assert False
```suggestion
        fail("Foi encontrado um mentor nao cadastrado")
```

2020-11-11 15:41 UTC, huandrey commented on python/__tests__/test_project_controller.py
> +    assert project.description == 'Com descrição'
:DD

2020-11-11 22:54 UTC, JuanBarros2 commented on python/models/project.py
> +            return True
```suggestion

```

2020-11-11 22:54 UTC, JuanBarros2 commented on python/models/project.py
> +        else:
```suggestion

```

2020-11-11 22:55 UTC, JuanBarros2 commented on python/models/project.py
> +            return False
```suggestion
```

2020-11-11 22:56 UTC, JuanBarros2 approved these changes

2020-11-17 23:59 UTC, merged