Adicionante testes de subscribers
OpenDevUFCG/Margaret pull request #23
Opened 2020-10-26 15:18 UTC by ummatias

Adicionando testes da classe subscribed e validações necessárias para a classe

2020-10-26 17:10 UTC, JuanBarros2 requested changes
Ficou bem legal os testes @ummatias ! Acho que tem alguns que nem precisavam estar aí, tipo email, name, porque não é a classe subscribed que tem a lógica do set. Outra coisa também, tenta guardar em vez de um valor numérico para o período, o período no formato "ANO.SEMESTRE" (exemplo: 2018.2)

2020-10-26 17:10 UTC, JuanBarros2 commented on python/__tests__/test_subscribed.py
> +        fail()
Boa! Nem sabia que tinha isso :D

2020-10-27 14:12 UTC, ummatias commented on python/__tests__/test_subscribed.py
> +        fail()
Né? Eu sabia que tinha no JUnity, ai fui na documentação do Pytest imaginando que teria algo parecido :)

2020-10-28 11:59 UTC, JuanBarros2 approved these changes
:rocket:

2020-10-28 19:22 UTC, caiodavic approved these changes

2020-10-28 22:11 UTC, merged