testes de project e organization
OpenDevUFCG/Margaret pull request #27
Opened 2020-10-28 08:27 UTC by gabriellytrajano

2020-10-28 11:55 UTC, JuanBarros2 requested changes

2020-10-28 11:55 UTC, JuanBarros2 commented on python/__tests__/test_organization.py
> +    org.add_project(1, "projeto1")
@gabriellytrajano É melhor passar o objeto projeto e não a string que representa ele. Se quisermos ter mais informações sobre o projeto não conseguiremos no cenário que está implementado atualmente

2020-10-28 11:55 UTC, JuanBarros2 commented on python/__tests__/test_organization.py
> +        assert False
Aqui tu pode usar o `fail('Mensagem de erro')` que Matias usou do pytest

2020-10-31 12:22 UTC, caiodavic approved these changes

2020-11-05 16:26 UTC, huandrey approved these changes

2021-02-04 22:52 UTC, closed without merging