Add rotas para list, add, remove e get Org
OpenDevUFCG/Margaret pull request #31
Opened 2020-11-07 02:54 UTC by ummatias

### Descrição da pull request:
Criando rotas:
*/organization/add (POST) => Adiciona organização / retorna ID
*/organization/list (GET) => Lista organizações
*/organization/remove (DELETE) => Remove organização por ID / retorna Org Removida
*/organization/org (GET) => Retorna Org por ID (ID passado por querry param (org_id)

### Categoria da Pull Request 

* [ ] Correção de bug  `bugfix` 
* [x] Adição de funcionalidade `feature`
* [ ] Refatoração de código  `chore`
* [ ] Atualização de dependências `update`
* [ ] Documentação  `docs`

***Informações adicionais:***

Utilizando classe User com owner (Precisa de revisão).

2020-11-07 13:03 UTC, JuanBarros2 requested changes
Ta ficando muito bom @ummatias ! ✨ Acabei esquecendo de falar sobre esses padrões de nomenclatura mas acho que é coisa besta pra mudar

2020-11-07 13:03 UTC, JuanBarros2 commented on python/ext/organization/organization.py
> +@org.route('/org', methods=['GET'])
Nesse caso aqui fica redundante colocar `/organization/org`. É melhor você passar `/organization/<id>` e [recuperar o parâmetro da URL](https://raccoon.ninja/pt/dev-pt/recuperando-argumentos-da-url-em-uma-aplicacao-flask-python/) mesmo

2020-11-07 13:03 UTC, JuanBarros2 commented on python/ext/organization/organization.py
> +orgC = OrganizationController()
Aqui talvez seja melhor renomear essa variável para que consigamos lembrar que é um controller

2020-11-08 22:12 UTC, JuanBarros2 commented on python/ext/organization/organization.py
> +            temp_org = orgs[i].__dict__
Aqui tem muita identação

2020-11-09 20:53 UTC, JuanBarros2 approved these changes

2020-11-11 16:58 UTC, caiodavic approved these changes

2020-11-11 22:38 UTC, merged