Adicionando rotas para buscar e atualizar orgs
OpenDevUFCG/Margaret pull request #34
Opened 2020-11-15 20:40 UTC by ummatias

### Descrição da pull request:
Acionando rotas para atualizar e buscar organizações através de atributos. Na busca o atributo é passado através querry params e na atualização de uma organização é passado através de um json.
### Categoria da Pull Request 

* [ ] Correção de bug  `bugfix` 
* [x] Adição de funcionalidade `feature`
* [ ] Refatoração de código  `chore`
* [ ] Atualização de dependências `update`
* [ ] Documentação  `docs`

***Informações adicionais:***
 Retornando UPDATED ao receber uma requisição para atualizar uma organização.

2020-11-15 21:15 UTC, JuanBarros2 approved these changes

2020-11-15 21:16 UTC, JuanBarros2 commented on python/util/validation.py
> +def validate_organization_existence(org_id, organizations):
Achei meio desnecessário esse método pq sinto que dava pra usar ele direto lá no get_organization. Mas de resto tudo top ✨

2020-11-15 22:12 UTC, ummatias commented on python/util/validation.py
> +def validate_organization_existence(org_id, organizations):
Ele já existia antes (dentro do controller), só movi pra classe de validação. Deixei pois tá sendo usando no get_org, remove_org e modify_org. Tu não acha que tirar ele vai resultar em muita repetição de código?

2020-11-17 12:35 UTC, JuanBarros2 requested changes

2020-11-17 12:35 UTC, JuanBarros2 commented on python/ext/organization/organization.py
> +@org.route('/<int:org_id>', methods=['Post'])
```suggestion
@org.route('/<int:org_id>', methods=['POST'])
```

2020-11-17 12:35 UTC, JuanBarros2 commented on python/ext/organization/organization.py
> +    return 'UPDATED'
Aqui o ideal era retornar o objeto Organization atualizado com o status code correto

2020-11-19 16:09 UTC, caiodavic approved these changes

2020-11-19 21:13 UTC, caiodavic approved these changes

2020-11-19 22:19 UTC, caiodavic approved these changes

2020-11-20 22:49 UTC, ummatias commented on python/ext/organization/organization.py
> +    return 'UPDATED'
Fiz a mudança pra retornar o objeto Organization, mas o que tu quer dizer com o "status code correto"?

2020-11-25 13:41 UTC, JuanBarros2 commented on python/ext/organization/organization.py
> +    return 'UPDATED'
Foi mal. Quis dizer método correto. Pelo que entendi isso aí ta atualizando uma organização né? Para updates 
é comum utilizar o PUT ou o PATCH (tem uma mini diferença que tu pode encontrar com mais detalhes [aqui](https://www.restapitutorial.com/lessons/httpmethods.html) )

2020-11-29 14:03 UTC, JuanBarros2 approved these changes

2020-11-29 17:47 UTC, merged