Base Implementation Organization Controller
OpenDevUFCG/Margaret pull request #6
Opened 2020-10-11 14:52 UTC by ummatias

Organization Controller creation and changing the exception types on Organization class

2020-10-11 15:16 UTC, huandrey reviewed
Acredito que por padrão o nome da classe tem que ser em CamelCase, mas o resto do código tá massa!!

2020-10-11 15:27 UTC, JuanBarros2 requested changes
@ummatias Tudo ótimo! Só remove o arquivo de cache do python que foi comitado

2020-10-11 15:27 UTC, JuanBarros2 commented on python/organization.py
> +            raise ValueError('Categoria Inválida')
Boa!

2020-10-12 00:23 UTC, ummatias reviewed
Mudado para CamelCase, obrigado @huandrey ^^

2020-10-12 00:24 UTC, ummatias commented
@JuanBarros2 Removido, não tinha visto que passou :)

2020-10-12 00:25 UTC, huandrey approved these changes

2020-10-12 14:16 UTC, JuanBarros2 commented on python/organizationController.py
> +        if atribute == 'name':
@ummatias como esse código está se repetindo muito, acho que tu poderia usar o método 
    `setattr(self, atribute, value)` que serve para setar um atributo. Aí vc passa o objeto, o nome do atributo que quer mudar e o valor. Economizaria muitos IFs

2020-10-12 14:16 UTC, JuanBarros2 commented on python/organizationController.py
> +                if organization.category.lower() == atribute_value.lower():
Mesma coisa para essa parte do código. O método `getattr(self, atribute) ` pode reduzir esses IFs que são feitos

2020-10-13 23:28 UTC, caiodavic approved these changes

2020-10-13 23:28 UTC, caiodavic approved these changes

2020-10-14 00:22 UTC, caiodavic approved these changes

2020-10-14 00:23 UTC, caiodavic approved these changes

2020-10-14 01:31 UTC, caiodavic approved these changes

2020-10-14 15:20 UTC, gabriellytrajano approved these changes

2020-10-14 18:29 UTC, ummatias commented on python/organizationController.py
> +        if atribute == 'name':
Realmente ótima ideia, já implementei ^^

2020-10-14 18:30 UTC, ummatias commented on python/organizationController.py
> +                if organization.category.lower() == atribute_value.lower():
Implementado ^^

2020-10-14 23:34 UTC, gabriellytrajano approved these changes

2020-10-16 13:54 UTC, JuanBarros2 approved these changes

2020-10-16 14:26 UTC, merged